### PR TITLE
add CI tests and remove dependency PlotUtils.jl

### PR DESCRIPTION
**Pull request by ranocha**
I was investigating latency of Trixi.jl. One of the reasons for quite a lot of invalidations was FixedPointNumbers.jl - which became a dependency because of TriplotRecipes.jl via PlotUtils.jl. Hence, I wanted to see where this is used and I could only find a use case for it when calling `RGB`. Thus, I replaced `RGB(0.7,1.0,0.8)` by `"LightCyan"`, which comes quite close as far as I can tell.

Since I wanted to be sure that everything still works, I wanted to run the tests. But there was no `test` folder, so I added the `examples` as basic tests and set up the corresponding GitHub actions for CI.

With Julia 1.8, I get on `master`
```julia
julia> @time_imports using TriplotRecipes
      0.1 ms  SnoopPrecompile
     52.0 ms  FixedPointNumbers
      0.2 ms  Reexport
     53.3 ms  ColorTypes 8.11% compilation time
    170.2 ms  Colors
      4.6 ms  IrrationalConstants
      0.5 ms  Compat
     90.1 ms  ChainRulesCore
      2.4 ms  DocStringExtensions 65.82% compilation time
      8.9 ms  ChangesOfVariables
      0.8 ms  InverseFunctions
      0.6 ms  LogExpFunctions
      0.1 ms  OpenLibm_jll
     15.0 ms  Preferences
      0.4 ms  JLLWrappers
      0.3 ms  CompilerSupportLibraries_jll
      2.2 ms  OpenSpecFun_jll 80.71% compilation time
     12.1 ms  SpecialFunctions
      0.2 ms  TensorCore
    118.2 ms  ColorVectorSpace 3.59% compilation time
     10.7 ms  ColorSchemes
    227.7 ms  PlotUtils
     29.6 ms  RecipesBase
      1.1 ms  TriplotBase
      0.8 ms  TriplotRecipes
```

With this branch, I get
```julia
julia> @time_imports using TriplotRecipes
      0.1 ms  SnoopPrecompile
     34.8 ms  RecipesBase
      1.0 ms  TriplotBase
      0.7 ms  TriplotRecipes
```
This does not even take the invalidations and their impact on latency later into account but should already be a nice latency improvement for us. A first test shows that it can reduce the latency of `using Trixi` by ca. 0.8 seconds.

### CODE REVIEW

**Comment by ranocha** [comment]
The invalidations CI run fails because of https://github.com/timholy/SnoopCompile.jl/issues/327

**Comment by ranocha** [comment]
Looks like CI passes. I will bump the version number to make it easier for you, @pazner, to release a new version.

**Comment by pazner** [comment]
Thanks @ranocha!

**Comment by sloede** [comment]
Great work, @ranocha, thanks for looking into this!

**Pull request merged**
